#!/bin/bash

# Check if --manager argument is provided
if [[ "$1" != "--manager" || -z "$2" ]]; then
    echo "Usage: $0 --manager {apt|yum|zypper}"
    exit 1
fi

# Select the package manager
manager="$2"

# Execute corresponding commands based on the chosen package manager
case $manager in
    apt)
        echo "Using APT package manager."
        sudo apt-get update
        sudo apt-get install build-essential libgl1-mesa-dev
	sudo apt install qt6-base-dev
        sudo apt install libspdlog-dev
	;;

    yum)
        echo "Using YUM package manager."
        sudo yum groupinstall "C Development Tools and Libraries"
        sudo yum install mesa-libGL-devel
	yum install spdlog
        ;;

    zypper)
        echo "Using Zypper package manager."
        sudo zypper refresh
        sudo zypper install -t pattern devel_basis
        sudo zypper in spdlog-devel
	;;

    *)
        echo "Unknown package manager: $manager"
        exit 1
        ;;
esac

# Exit the script
exit 0

